[en]
title = "Robson Cassiano"
contentDir = "content/english"
weight = 1
LanguageName = "English"


[pt-br]
title = "Robson Cassiano"
description = "Becoming a Full Stack Human"
contentDir = "content/portuguese" 
weight = 1
LanguageName = "Português"
