  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/pt-br/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/pt-br/post/"

  [[main]]
  name = "Aforismos"
  weight = 200
  identifier = "aforismos"
  url = "/pt-br/aforismos/"

  [[main]]
  name = "Sobre mim"
  weight = 300
  identifier = "about"
  url = "/pt-br/sobre-mim/"

  [[main]]
  name = "Contato"
  weight = 400
  identifier = "contact"
  url = "/pt-br/contato/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/pt-br/imprint/"
